USE [master]
GO

/****** Object:  Database [CustomDB]    Script Date: 2/25/2021 12:44:18 PM ******/
CREATE DATABASE [CustomDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'CustomDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\CustomDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'CustomDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\CustomDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [CustomDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [CustomDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [CustomDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [CustomDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [CustomDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [CustomDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [CustomDB] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [CustomDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [CustomDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [CustomDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [CustomDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [CustomDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [CustomDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [CustomDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [CustomDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [CustomDB] SET  ENABLE_BROKER 
GO

ALTER DATABASE [CustomDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [CustomDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [CustomDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [CustomDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [CustomDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [CustomDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [CustomDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [CustomDB] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [CustomDB] SET  MULTI_USER 
GO

ALTER DATABASE [CustomDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [CustomDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [CustomDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [CustomDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [CustomDB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [CustomDB] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [CustomDB] SET QUERY_STORE = OFF
GO

ALTER DATABASE [CustomDB] SET  READ_WRITE 
GO

